apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopping-mart-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: shopping-mart.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shopping-mart-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: shopping-mart-backend
            port:
              number: 5000
