apiVersion: v1
kind: Secret
metadata:
  name: shopping-mart-secrets
type: Opaque
stringData:
  mongodb-uri: "mongodb://admin:SecurePassword123@mongodb:27017/shopping-mart"
  mongodb-username: "admin"
  mongodb-password: "SecurePassword123"
